/* Auto-generated by genmsg_cpp for file /home/ss/work/motionplanning/autocar/msg/controlCommand.msg */
#ifndef AUTOCAR_MESSAGE_CONTROLCOMMAND_H
#define AUTOCAR_MESSAGE_CONTROLCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace autocar
{
template <class ContainerAllocator>
struct controlCommand_ {
  typedef controlCommand_<ContainerAllocator> Type;

  controlCommand_()
  : acc(0.0)
  , yaw(0.0)
  {
  }

  controlCommand_(const ContainerAllocator& _alloc)
  : acc(0.0)
  , yaw(0.0)
  {
  }

  typedef float _acc_type;
  float acc;

  typedef float _yaw_type;
  float yaw;


  typedef boost::shared_ptr< ::autocar::controlCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::autocar::controlCommand_<ContainerAllocator>  const> ConstPtr;
}; // struct controlCommand
typedef  ::autocar::controlCommand_<std::allocator<void> > controlCommand;

typedef boost::shared_ptr< ::autocar::controlCommand> controlCommandPtr;
typedef boost::shared_ptr< ::autocar::controlCommand const> controlCommandConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::autocar::controlCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::autocar::controlCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace autocar

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::autocar::controlCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::autocar::controlCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::autocar::controlCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "28f23c7e5636e15985dc527e33bca955";
  }

  static const char* value(const  ::autocar::controlCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x28f23c7e5636e159ULL;
  static const uint64_t static_value2 = 0x85dc527e33bca955ULL;
};

template<class ContainerAllocator>
struct DataType< ::autocar::controlCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "autocar/controlCommand";
  }

  static const char* value(const  ::autocar::controlCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::autocar::controlCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 acc\n\
float32 yaw\n\
\n\
";
  }

  static const char* value(const  ::autocar::controlCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::autocar::controlCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::autocar::controlCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.acc);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct controlCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::autocar::controlCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::autocar::controlCommand_<ContainerAllocator> & v) 
  {
    s << indent << "acc: ";
    Printer<float>::stream(s, indent + "  ", v.acc);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // AUTOCAR_MESSAGE_CONTROLCOMMAND_H

